# Generated by Django 4.2.1 on 2025-04-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='state',
            new_name='phone',
        ),
    ]
